version: "3"

networks:
  sys:
    external: true

services:
  gitclone:
    image: gopherconbr-2024-emb-languages/git-clone
    container_name: gitclone
    environment:
      - GITHUB_REPOSITORY=https://paulo:d9b94812ee918ac104d990d32be07857b8beac48@gitea.digitalcircle.com.br/dc_edge/sample_config.git
      - GIT_CLONE_DIR=/gitroot
      - GIT_PUSH_FREQUENCY=5s
    volumes:
      - ./stage/gitroot:/gitroot
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - sys
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"