@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Usuario as user
control "Motor de Calculo" as microservice
control IAM as iam
database Git as git

user -> microservice : Aciona api de cálculo
microservice -> iam : Verifica credenciais para cálculo
iam --> microservice: Autoriza cálculo
microservice -> git : Busca versão atualizada da fórmula (git pull)
git --> microservice: Retorna fórmula atualizada
microservice -> microservice: Realiza cálculo com input
microservice -> microservice: Calcula hashes utilizando hash do microservico e da fórmula
microservice --> user: Devolve saida com input, output, hashes.

@enduml